### ISSUE TITLE
Customize renderSuggestion on react-autosuggest

### ISSUE THREAD

**Issue by josephdburdick** [moroshko/react-autowhatever#15]
Hi, awesome work on this. It does 99% of what I need it to do but it appears there is one place it falls short: highlighting the matching string against what the user is searching for. Here: https://github.com/moroshko/react-autowhatever/blob/master/src/Item.js#L71 I want to be able to insert customizable HTML here versus just having a string. 

For my purposes this would be used for highlighting matching search results by value stored in state and wrapping the matched string in `<strong>` tags.

**Comment by moroshko** [comment]
Hey @josephdburdick,

Check out [react-autosuggest](https://github.com/moroshko/react-autosuggest), it might be what you need.

If not, have a look at [this example](https://github.com/moroshko/react-autosuggest/blob/655458c16eea13e9f61c8a0add1f06c283768d97/demo/src/components/App/components/Examples/components/CustomRender/CustomRender.js#L30-L51). Your `renderItem` should look similar to `renderSuggestions` in this example.
