### ISSUE TITLE
Any plans to add support for contenteditable divs in the future?

### ISSUE THREAD

**Issue by sahilamoli** [moroshko/react-autowhatever#17]
It would be awesome to use this to build functionality where the input element can accept rich text (@mentions, tagging, etc.). Since `<input>` is only plain text, the only way to do it would be with `<div contenteditable="true"></div>`. Any plans on supporting this in the future?

**Comment by acierto** [comment]
I think if you will create a PR yourself it will be included to this library way faster :)

**Comment by sahilamoli** [comment]
Ended up using Facebooks draftJS with mentions plugin. Worked great for this use case.
