### ISSUE TITLE
React warning

### ISSUE THREAD

**Issue by ZachBray** [moroshko/react-autowhatever#2]
Thank you for the great library. I'm using it via react-autosuggest.

I've noticed that I get a warning when I have multiple ~~selections~~ _suggestions_:

```
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `Autowhatever`. See https://fb.me/react-warning-keys for more information
```

It looks like `renderItemsList(...)` isn't adding a key to the items it returns.

**Comment by moroshko** [comment]
@ZachBray What do you mean by multiple selections? (Do you mean multiple sections?)

What React version are you using? I was under impression that specifying a `key` is optional in the latest React versions.

Could you share a Codepen that demonstrates the issue?

**Comment by ZachBray** [comment]
I'm using React v0.14.7

**Comment by moroshko** [comment]
I believe this is not an issue anymore since 3.2.0. Let me know if you still this error.
