### ISSUE TITLE
How to use custom scrollbar components with react-autowhatever?

### ISSUE THREAD

**Issue by sivadass** [moroshko/react-autowhatever#22]
I can't find any markups to wrap custom scrollbar components with search suggestion? How do I can customize the scrollbar?

**Comment by moroshko** [comment]
Is there any specific custom scroll bar library that you are trying to integrate with `react-autowhatever`?

**Comment by sivadass** [comment]
Yeah, we are using [react-custom-scroobars](https://github.com/malte-wessel/react-custom-scrollbars)

**Comment by moroshko** [comment]
[Here](http://codepen.io/moroshko/pen/dpgOOQ?editors=0010) is my attempt to integrate with `react-custom-scrollbars`. I hope you can take it from here.

**Comment by sivadass** [comment]
Thanks you so much @moroshko  :)
