### ISSUE TITLE
Please stop using React.PropTypes that is deprecated

### ISSUE THREAD

**Issue by agusbrand** [moroshko/react-autowhatever#27]
Use of React.PropTypes now is deprecated according to: https://facebook.github.io/react/warnings/dont-call-proptypes.html

Thanks

**Comment by ruiwei** [comment]
Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

**Comment by moroshko** [comment]
This is solved in [v10.0.0](https://github.com/moroshko/react-autowhatever/releases/tag/v10.0.0).
