### ISSUE TITLE
Unique Keys Required For All Themeable Elements

### ISSUE THREAD

**Issue by TigerC10** [moroshko/react-autowhatever#7]
Per [react-themeable](https://github.com/markdalgleish/react-themeable):
> Note: A unique key for each themed element is required for Radium to work correctly.

I've noticed that I can't get rid of the browser's default focus ring around the input field for [react-autosuggest](https://github.com/moroshko/react-autosuggest) using [Radium](https://github.com/FormidableLabs/radium).  When I start to trace through, I notice that this project doesn't provide unique `key` props to all of the elements using [react-themeable](https://github.com/markdalgleish/react-themeable).

Need to add unique `key` props to all themeable elements to make this actually compatible with [Radium](https://github.com/FormidableLabs/radium).

**Comment by moroshko** [comment]
> I notice that this project doesn't provide unique key props to all of the elements using react-themeable.

Which elements don't provide a unique key? Pull Request is welcome!

**Comment by TigerC10** [comment]
[React](https://github.com/facebook/react) doesn't require `key` props unless you've got sibling components.  So, that's likely why this isn't a current issue.  Unfortunately it's [react-themeable](https://github.com/markdalgleish/react-themeable) that requires the addition of keys for [Radium](https://github.com/FormidableLabs/radium) compatibility.

By my count, 7 elements use [react-themable](https://github.com/markdalgleish/react-themeable) that do not have `key` properties on them.  There's an outstanding PR - but at present, they are:

[Autowhatever.js: Line 115](https://github.com/moroshko/react-autowhatever/blob/master/src/Autowhatever.js#L115)

[Autowhatever.js: Lines 134-136](https://github.com/moroshko/react-autowhatever/blob/master/src/Autowhatever.js#L134)

[Autowhatever.js: Line 150](https://github.com/moroshko/react-autowhatever/blob/master/src/Autowhatever.js#L150)

[Autowhatever.js: Line 154](https://github.com/moroshko/react-autowhatever/blob/master/src/Autowhatever.js#L154)

[Autowhatever.js: Lines 173-175](https://github.com/moroshko/react-autowhatever/blob/master/src/Autowhatever.js#L173)

[Autowhatever.js: Line 232](https://github.com/moroshko/react-autowhatever/blob/master/src/Autowhatever.js#L232)

[Autowhatever.js: Line 233](https://github.com/moroshko/react-autowhatever/blob/master/src/Autowhatever.js#L233)

Should be as easy as throwing a `key` property on each of these tags.  I'm given to understand it's an all or nothing thing, [Radium](https://github.com/FormidableLabs/radium) won't work unless everything using [react-themable](https://github.com/markdalgleish/react-themeable) has a key.

**Comment by TigerC10** [comment]
Why the revert?

**Comment by TigerC10** [comment]
Okay, yes - looks like it's working great. 😄  I like this better too.
